# Generated by Django 6.0.5 on 2026-06-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otp_alter_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expiration_data',
            new_name='created_at',
        ),
    ]
