# Generated by Django 6.0.5 on 2026-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
