# Generated by Django 6.0.5 on 2026-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_otp_failed_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
