# Generated by Django 6.0.5 on 2026-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_otp_verified_alter_otp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='failed',
        ),
        migrations.AddField(
            model_name='otp',
            name='failed_times',
            field=models.IntegerField(default=0),
        ),
    ]
