# Generated by Django 6.0.5 on 2026-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_otp_failed_otp_failed_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='failed_times',
        ),
        migrations.AddField(
            model_name='otp',
            name='failed',
            field=models.BooleanField(default=True),
        ),
    ]
