# Generated by Django 6.0.5 on 2026-05-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='perent',
            new_name='parent',
        ),
    ]
